name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] #push가 되었을때 작동을 하겠다.

jobs: # 무슨 일을 할 것이냐
  build-and-push: # 
    runs-on: ubuntu-latest
    steps: # steps - - 로 분리되어있는데 하나의 과정이다.
      - name: Checkout # checkout ?
        uses: actions/checkout@v3 # github에 이미 있는 action이름, @뒤는 v3 = version3

      - name: Log in to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app image # 이미지 파일을 만들어서 dockerhub에다가 올리고 # 이미지를 만들때 github쪽 자원을 쓴다 -> 우리 자원 안씀
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-ncp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/my-ncp:${{ github.sha }}

  deploy: #html이 다르게 있으면 글자를 수정한다 -> 공인 IP에 뜨는 웹사이트에서 바꾸고싶다면 -> root ssh로 들어가서 git clone을 해야하는데 그것의 자동화
    needs: build-and-push
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3 #github actions가 봇

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.NCP_HOST }} >> ~/.ssh/known_hosts

      - name: Copy deploy files # Copy deploy files
        run: |
          scp -i ~/.ssh/id_rsa -r docker-compose.yml nginx \
            ${{ secrets.NCP_USER }}@${{ secrets.NCP_HOST }}:/tmp/my_repo/

      - name: Deploy on NCP
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.NCP_USER }}@${{ secrets.NCP_HOST }} "
            cd /tmp/my_repo &&
            systemctl stop nginx || true &&
            systemctl disable nginx || true &&
            docker compose pull &&
            docker compose up -d --remove-orphans
          "